# Gemfile for RoundCaddy iOS
# Run `bundle install` to install dependencies

source "https://rubygems.org"

gem "fastlane", "~> 2.220"

# Optional plugins
# gem "fastlane-plugin-firebase_app_distribution"
# gem "fastlane-plugin-badge"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
