name: RoundCaddy
options:
  bundleIdPrefix: com.roundcaddy
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    # Apple Developer Team ID
    DEVELOPMENT_TEAM: "AYEZVE9ZJ6"
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"
    # App Store optimization
    ENABLE_BITCODE: false
    DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    # Archive settings
    SKIP_INSTALL: false
    INSTALL_PATH: "$(LOCAL_APPS_DIR)"
  configs:
    Debug:
      DEBUG_INFORMATION_FORMAT: dwarf
    Release:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
      SWIFT_OPTIMIZATION_LEVEL: "-O"
      SWIFT_COMPILATION_MODE: wholemodule

targets:
  RoundCaddy:
    type: application
    platform: iOS
    sources:
      - path: GolfStats/Sources
        type: group
      - path: GolfStats/Resources
        type: group
        buildPhase: resources
        excludes:
          - "**/Info.plist"
          - "**/*.entitlements"
    settings:
      base:
        INFOPLIST_FILE: GolfStats/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.roundcaddy.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        ENABLE_PREVIEWS: true
        # App Store requirements
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
    entitlements:
      path: GolfStats/Resources/GolfStats.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        com.apple.security.application-groups:
          - group.com.roundcaddy
    preBuildScripts: []
    postBuildScripts: []
    dependencies:
      - target: RoundCaddyWatch
        embed: true

  RoundCaddyWatch:
    type: application
    platform: watchOS
    sources:
      - path: ../watch/RoundCaddyWatch WatchKit Extension/Sources
        type: group
      - path: ../watch/RoundCaddyWatch WatchKit Extension/Resources
        type: group
        buildPhase: resources
        excludes:
          - "Info.plist"
          - "*.entitlements"
    settings:
      base:
        INFOPLIST_FILE: ../watch/RoundCaddyWatch WatchKit Extension/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.roundcaddy.ios.watchkitapp
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_OTHER_FLAGS: --enable-icon-stack-fallback-generation=disabled
        ENABLE_PREVIEWS: true
        SKIP_INSTALL: true
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
        # Watch app embedding
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        CODE_SIGN_ENTITLEMENTS: ../watch/RoundCaddyWatch WatchKit Extension/Resources/RoundCaddyWatch.entitlements

  RoundCaddyTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GolfStatsTests
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.roundcaddy.ios.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/RoundCaddy.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/RoundCaddy"
        BUNDLE_LOADER: "$(TEST_HOST)"
        SWIFT_VERSION: "5.9"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - target: RoundCaddy
        embed: false

schemes:
  RoundCaddy:
    build:
      targets:
        RoundCaddy: all
        RoundCaddyWatch: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - RoundCaddyTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

  RoundCaddyWatch:
    build:
      targets:
        RoundCaddyWatch: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
