name: GolfStats
options:
  bundleIdPrefix: com.golfstats
  deploymentTarget:
    iOS: "18.0"
    watchOS: "11.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    SWIFT_VERSION: "5.9"

targets:
  GolfStats:
    type: application
    platform: iOS
    sources:
      - path: GolfStats/Sources
        type: group
      - path: GolfStats/Resources
        type: group
    settings:
      base:
        INFOPLIST_FILE: GolfStats/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.golfstats.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        SUPPORTS_MACCATALYST: false
        ENABLE_PREVIEWS: true
    entitlements:
      path: GolfStats/Resources/GolfStats.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    preBuildScripts: []
    postBuildScripts: []
    dependencies: []

schemes:
  GolfStats:
    build:
      targets:
        GolfStats: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
